title: Multi-modal Video Understanding in a Noisy Environment
description:
  - ACM Multimedia Asia 2021 Grand Challenge, Oct 2021, Chengdu, China
buttons:
  Overview: "#overview"
  Task Descriptions: "#overview"
  About the Dataset: "#overview"
  Important Dates: "#overview"
  Instructions: "#overview"
  Organizers: "#overview"
  Volunteers: "#overview"

show_downloads: false
theme: jekyll-theme-cayman
